# Config for running the InferenceRecipe in generate.py to generate output
# from Llama2 7B model
#
# This config assumes that you've run the following command before launching
# this run:
#   tune download meta-llama/Llama-2-7b-hf --output-dir /tmp/Llama-2-7b-hf --ignore-patterns "*.safetensors" --hf-token <HF_TOKEN>
#
# To launch, run the following command from root torchtune directory:
#    tune run generate --config generation

output_dir: /tmp/torchtune/qwen2_5_3B_blt/generate

# Model arguments
model:
  _component_: ttblt.bltqwen.qwen2_5_blt
  use_hash_ngrams: 1
  patch_size: 8
  encoder_num_layers: 3
  encoder_num_cross_layers: 1
  decoder_num_layers: 9
  decoder_num_cross_layers: 3
  entropy_model_path: ~/models/entropy_model/best.pt
  entropy_threshold: 1.335
  max_patch_size: 0

checkpointer:
  _component_: torchtune.training.FullModelMetaCheckpointer
  #checkpoint_dir: /tmp/torchtune/qwen2_5_3B_blt_test/full_single_device/epoch_3
  #checkpoint_dir: /tmp/torchtune/qwen2_5_3B_blt/full_single_device/epoch_25  
  checkpoint_dir: /home/ianbarber/models/ttblt_v2_entropy/full_single_device/epoch_2
  #checkpoint_dir: /tmp/torchtune/qwen2_5_3B_blt/full_single_device/epoch_0                                                 
  #checkpoint_dir: /tmp/torchtune/qwen2_5_3B_blt/full_single_device/epoch_3
  checkpoint_files: [
    adapter_model.pt
  ]
  recipe_checkpoint: null
  output_dir: ${output_dir}
  model_type: REWARD

device: cuda
dtype: bf16

seed: 1234

# Tokenizer arguments
tokenizer:
  _component_: ttblt.bltqwen.blt_tokenizer
  max_seq_len: 4096

# Generation arguments; defaults taken from gpt-fast
prompt:
  user: "Below is an instruction that describes a task. Write a response that appropriately completes the request.\n\n### Instruction:\nTell me about cats\n\n### Response:\n\n"
max_new_tokens: 500
temperature: 0.7
top_k: 50 # Smaller, bytes! 

enable_kv_cache: False # Issue with cross-attention

quantizer: null
